### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by beilmanmich** [bennylope/activecampaign#1]
Is one able to update custom fields using client.contacts.sync? Do you have any examples?

**Comment by bennylope** [comment]
> Is one able to update custom fields using client.contacts.sync? Do you have any examples?

Yes! _**But...**_

You need to know the field ID in question and then make sure to include in a double splat prefaced dictionary.

### Standard syncing

If you're syncing `bob@acme.com`, you can do it like so:

```python
client.contacts.sync(email="bob@acme.com", first_name="Jim")
```

### Adding a custom field

But if you want to sync a custom field, you need to provide the field ID. And that needs to be in the format of `field[ID,0]`, e.g. `field[345,0]`. The `0` you have to leave in place

> Custom field values. Example: field[345,0] = 'value'. In this example, "345" is the field ID. Leave 0 as is.

So to sync the value `January` to `bob@acme.com` in the custom field with ID 1:

```python
client.contacts.sync(**{"email": "bob@acme.com", "first_name": "Jim", "field[1,0]": "January"})
```

### Getting the field ID

How do you find the ID of a custom field? I don't know any way of doing this other than using the browser's network inspector to check the JSON request in the ActiveCampaign dashboard, but that does work.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/102509/60989061-ffed6e80-a312-11e9-98c5-8db17fedbf0a.png">

The latest API might make this simpler, I'm not sure, but this package still uses version 1.

**Comment by beilmanmich** [comment]
Thank you so much for the clear documentation, this works great!

Appreciate your efforts on this, keep up the great work!!

**Comment by hoaiphongt** [comment]
Hi @bennylope , I knew the version 3 using json with format
```
{
	"contact": {
		"email": "johndoe@example.com",
		"firstName": "John",
		"lastName": "Doe",
		"fieldValues": [{
				"field": "1", => field ID
				"value": "The Value for First Field"
			},
			{
				"field": "6", => fieldID
				"value": "2008-01-20"
			}
		]
	}
}
```
- About check field Id in some cases is difficult to know  because we have many, I checked Version 1 https://www.activecampaign.com/api/overview.php, it allows us can update by Personalization Tag : EX %FIRSTNAME%> I would like to ask V3 of API can update contact info by Personalization Tag or it's only support fieldID. 
- Thank you
